name: "Deploy"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-notifier:
    name: "Build Notifier Lambda"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/notifier

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Setup Cargo Lambda
        run: pip3 install cargo-lambda

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo lambda build --release --arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: notifier-lambda
          path: target/lambda/notifier-lambda/
          if-no-files-found: error
          retention-days: 1

  build-callback:
    name: "Build Callback Lambda"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/callback

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Setup Cargo Lambda
        run: pip3 install cargo-lambda

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo lambda build --release --arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: callback-lambda
          path: target/lambda/callback-lambda/
          if-no-files-found: error
          retention-days: 1

  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: [build-notifier, build-callback]

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Notifier Function Artifact
        uses: actions/download-artifact@v8
        with:
          name: notifier-lambda
          path: ./notifier-lambda

      - name: Download Callback Function Artifact
        uses: actions/download-artifact@v8
        with:
          name: callback-lambda
          path: ./callback-lambda

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.13"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          mask-aws-account-id: true
          aws-region: us-east-1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: production
    needs: [build-notifier, build-callback, plan]

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Notifier Function Artifact
        uses: actions/download-artifact@v8
        with:
          name: notifier-lambda
          path: ./notifier-lambda

      - name: Download Callback Function Artifact
        uses: actions/download-artifact@v8
        with:
          name: callback-lambda
          path: ./callback-lambda

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.13"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          mask-aws-account-id: true
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
